home/urls.py
from django.urls import path 
from django.views.generic import TemplateView 
from .views import OfferView,  OfferApplyView, ContactView


app_name = 'home'
urlpatterns = [
  path('', TemplateView.as_view(template_name="home/index.html"), name="index"),
  path('services', TemplateView.as_view(template_name="home/services.html"), name="services"),
  path('offers', OfferView.as_view(), name="offer"),
  path('offers/<str:slug>/apply', OfferApplyView.as_view(), name="apply"),
  path('about-us', TemplateView.as_view(template_name = "home/about-us.html"), name="about-us"),
  path('contact-us', ContactView.as_view(), name="contact-us"),
]

m4_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
    
]

home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify


# Create your models here.

class Offers(models.Model):
  contrat_type =  [
    ('CDI', 'CDI'),
    ('CDD', 'CDD'),
    ('Stage', 'Stage'),
]
  searching_for = models.CharField(max_length=255, verbose_name='post')
  slug = models.SlugField(null=True, blank=True)
  contract = models.CharField(max_length=10, choices=contrat_type, default=contrat_type[0], verbose_name='type_de_contact')
  post_number = models.PositiveIntegerField(default=1)
  description = RichTextField()
  looking_for = RichTextField()
  experience = models.CharField(max_length=255)
  region = models.CharField(max_length=255)
  
  
  
  def __str__(self): 
    return self.searching_for 
  
  def save(self , *args, **kwargs):
    self.slug = slugify(self.searching_for + '-' + self.region)
    return super().save(*args, **kwargs)
  
  class Meta: 
    verbose_name_plural = 'offers'
  

home/forms.py
from django import forms
from django.template.loader import render_to_string
from .email_thread import EmailThread
from .utils import cleaned_field

class ContactForm(forms.Form):

    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'votre nom',
            'name': "name",
        }))
    email = forms.EmailField(max_length=60, widget=forms.EmailInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'votre email',
            'name': 'email',
        }
    ))
    cellphone = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'input-box',
        'placeholder': 'votre téléphone',
        'name': 'cellphone',
    }))
    content = forms.CharField(max_length=500, widget=forms.Textarea(
        attrs={
            'class': 'input-box',
            'placeholder': 'message',
            'name': 'content',
        }
    ))
    subject = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={

            'class': 'input-box',
            'placeholder': 'sujet ',
            'name': 'subject',
        }))

    def send_email(self):
        fields_value = cleaned_field(self)
        html = render_to_string('home/components/contact_form.html', {**fields_value})
        email_thread = EmailThread(fields_value.get('subject'), fields_value.get('content'), fields_value.get('email'), html, [
                                   'danidkm242@gmail.com'])
        email_thread.start()
        email_thread.join()
        return email_thread.status


class ApplyingForm(forms.Form): 
    civility = [
        ('Mrs', 'Mrs'),
        ('Mme', 'Mme'), 
        ]
        
     
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'votre nom',
            'name': "name",
        }))
    email = forms.EmailField(max_length=60, widget=forms.EmailInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'votre email',
            'name': 'email',
        }
    ))
    cellphone = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'input-box',
        'placeholder': 'Tel (ex : 064649019) ',
        'name': 'cellphone',
    }))
    content = forms.CharField(max_length=500, widget=forms.Textarea(
        attrs={
            'class': 'input-box',
            'name': 'content',
            'placeholder': 'votre message',
        }
    ))
  
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class': 'input-box',
            'placeholder': 'votre prenom',
            'name': "name",
        }))
    
    cv  = forms.FileField();

  
    def send_email(self, file, offer_post):
        fields_value = cleaned_field(self)
        html = render_to_string('home/components/offer_applying.html', {**fields_value, 'post': offer_post})
        email_thread = EmailThread(fields_value.get('offer'), fields_value.get('content'), fields_value.get('email'), html, [
                                   'danidkm242@gmail.com'], (file.name , file.read(), file.content_type))
        email_thread.start()
        email_thread.join()
        return email_thread.status

home/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import JsonResponse
from .forms import ContactForm, ApplyingForm
from .models import Offers
from .utils import is_valid_extension
# Create your views here.



class OfferView(View):

    def get(self, request):
        offers = Offers.objects.all()
        return render(request, 'home/offers.html', context={'offers': offers})


class OfferApplyView(View):
    def get(self, request, slug):
        job_to_applying = get_object_or_404(Offers, slug=slug)
        return render(request, 'home/apply_job.html', context={'job': job_to_applying, 'form': ApplyingForm})

    def post(self, request, slug):
        allowed_extension = ('pdf')
        form = ApplyingForm(request.POST, request.FILES)
        if form.is_valid():
            offer = get_object_or_404(Offers, slug=slug)
            file = request.FILES.get('cv')
            is_valid_ext, extension = is_valid_extension(
                file.name, allowed_extension)
            if not is_valid_ext:
                status = "error"
                return JsonResponse({'message': f"L'extension de fichier {extension} n'est pas permise ", "status": status})

        status = form.send_email(file, offer.searching_for)

        if not status == "success":
            return JsonResponse({'message': "Envoie echoué, Veuillez Ressayer", "status": status})
        return JsonResponse({"message": "Mail Envoyé", "status": status})


class ContactView(View):
    def get(self, request):
        return render(request, 'home/contact-us.html', context={'form': ContactForm})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            status = form.send_email()
        if not status == "success":
            return JsonResponse({'message': "Envoie echoué, Veuillez Ressayer", "status": status})
        return JsonResponse({"message": "Mail Envoyé", "status": status})

home/templates/home/about-us.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
/>
{% endblock %} {%block content %} {% include 'home/components/header.html' %}
<section class="hero hero--small"></section>

<section>
  <h1 class="heading">
    Pourquoi nous faire <span class="heading--primary">Confiance ?</span>
  </h1>
  <div class="container container--center">
    <p class="container__text">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit nisi voluptas
      impedit delectus modi consectetur necessitatibus nulla nihil, repellendus
      autem.
    </p>
  </div>
</section>
<section>
  <h1 class="heading">Notre <span class="heading--primary">Slogan</span></h1>
  <div class="container container--center">
    <p class="container__text">
      savoir être, savoir faire, l’éfficacité, la rigueur sont nos valeurs
    </p>
  </div>
</section>

<section class="legal-info">
  <h1 class="heading">Informations</h1>
  <div class="legal-container">
    <div class="legal-box">
      <h2>DATE DE CREATION</h2>
      <p>2017</p>
    </div>
    <div class="legal-box">
      <h2>SARL</h2>
      <p>Capital: 10<span>M</span></p>
    </div>
    <div class="legal-box">
      <h2>RCCM</h2>
      <p>16B1166</p>
    </div>
    <div class="legal-box">
      <h2>NUI</h2>
      <p>M2016110000997178</p>
    </div>
  </div>
</section>

<section class="team">
  <div class="grid grid--autofit-20 grid--gap-1">
    <div class="team__card">
      
        <img src="{% static 'home/assets/images/value.png' %}" alt="" />
      
      <div class="team__card-title">
        <h2>Lorem, ipsum.</h2>
        <h3 class="card_subtitle">Lorem ipsum dolor sit amet consectetur.</h3>
      </div>
    </div>

    <div
      class="team__card team__card--text"
      style="background: rgb(101, 218, 91)"
    >
      <h1>NOTRE EQUIPE</h1>
      <p class="card_subtitle">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga fugit
        deserunt voluptates necessitatibus reprehenderit! Aliquid soluta
        similique mollitia excepturi facere at ullam cumque deleniti porro,
        molestiae veritatis, et sed reiciendis.
      </p>
    </div>

    <div class="team__card">
      <img src="{% static 'home/assets/images/testimonial.jpg' %}" alt="" />
      <div class="team__card-title">
        <h2>Lorem, ipsum.</h2>
        <h3 class="card_subtitle">Lorem ipsum dolor sit amet consectetur.</h3>
      </div>
    </div>

    <div class="team__card">
      <img src="{% static 'home/assets/images/testimonial.jpg' %}" alt="" />
      <div class="team__card-title">
        <h2>Lorem, ipsum.</h2>
        <h3 class="card_subtitle">Lorem ipsum dolor sit amet consectetur.</h3>
      </div>
    </div>
  </div>
</section>

<section class="location">
  <h1 class="heading">Nos branches</h1>

  <div class="location-container">
    <div class="location-box">
      <div class="location-icon fas fa-warehouse"></div>
      <h2>Pointe noire</h2>
    </div>
    <div class="location-box">
      <div class="location-icon fas fa-warehouse"></div>
      <h2>Brazzaville</h2>
    </div>
  </div>
</section>

{% include 'home/components/footer.html' %} {% endblock%}

home/templates/home/activity.html
{% extends 'base.html' %} {% load static %} {% block head %} {% endblock %}
{%block content %} {% include 'home/components/header.html' %} {% include
'home/components/footer.html' %} {% endblock%}

home/templates/home/apply_job.html
{% extends 'base.html' %} 
{% block head %} {% endblock %} 
{% block content %} 
{%include 'home/components/header.html' %}

<section class="">
  <h3 class="heading">Postulez</h3>
  <form method="post" class="box form" enctype="multipart/form-data" >
    <p class="text-action"></p>
    <div class="load"></div>
    {% csrf_token %} 
    {{ form.last_name }} 
    {{ form.email }} 
    {{ form.first_name }}
    {{ form.offer }}
    {{ form.cellphone }} 
    {{ form.content }}
    <div style="text-align: left">{{ form.cv }}</div>
    <input type="submit" value="Envoyez" class="btn" />
  </form>
</section>
{% include 'home/components/footer.html' %} {% endblock %}

home/templates/home/components/contact_form.html
{% include 'home/components/mail_style.html' %}
<h2 class="heading"> Soumission du formulaire de contact<h2>
<p><b>Nom: </b>{{ name }}</p>
<p><b>Objet: </b>{{ subject }}</p>
<p><b>E-mail: </b>{{ email }}</p>
<p><b>Telephone: </b>0{{ cellphone }}</p>
<div class="message">
  <p> {{ content }}</p>
</div> 
<a href="mailto:{{ email }}" class="btn">Repondre</a>
</center>

home/templates/home/components/footer.html
<footer class="credit">
  <p>site realisé par <span>Blue Id</span> | tout droit reservé </p>

  <div class="share">
     <a href="#gmail" class="share__item fab fa-facebook"></a>
     <a href="#facebook" class="share__item fas fa-envelope"></a>
     <a href="#linkedin" class="share__item fab fa-linkedin"></a>
     <a href="#instagram" class="share__item fab fa-instagram"></a>
  </div>
</footer>

home/templates/home/components/header.html
{% load static %}
<header class="header" data-aos="menu-area" >
  <div class="logo">
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/Logovalidé.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/Logovalidé.png' %}"
      />
      <img src="{% static 'home/assets/images/Logovalidé.png' %}" alt="M4 Logo" class="" />
    </picture>
  </div>
  <nav class="navbar">
    <a href="{% url 'home:index'%}" class="nav__item">accueil</a>
    <a href="{% url 'home:about-us' %}" class="nav__item">qui somme nous</a>
    <a href="{% url 'home:services' %}" class="nav__item">services</a>
    <a href="{% url 'home:offer' %}" class="nav__item">nos offres</a>
    <a href="{% url 'home:contact-us' %}" class="nav__item">Contact</a>
  </nav>
  <img src="{% static 'home/assets/icons/menu.svg' %} " alt="menu bar bouton " id="menu-btn" />
  <div class="scroll-indicator"></div>
  
</header>

home/templates/home/components/mail_style.html
<head> 
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Nunito:ital,wght@0,200;0,300;0,600;1,300&display=swap" rel="stylesheet">
  <style type="text/css" >
    *{
      font-family: 'Nunito', sans-serif;
      text-decoration: none;
    }
    .heading {
      font-size: 1.5rem;
      color: #23c13d;   
    }
  p{
     font-size: 1.3rem;
     font-weight: 300;
  }
  .btn {
  margin-top: 1rem;
  display: inline-block;
  padding: 1rem 2.8rem; 
  padding-right: 3rem;
  background: linear-gradient(130deg, #23c13d 93%, transparent 90%);
  text-align: center;
  color: #fff;
  cursor: pointer;
  font-size: 1.3rem;
}
.message{
  background: #F1F7FE; 
  border-radius: 15px;
  padding: 2rem 1rem;
}
.message p{
  line-height: 1.2;
  color: black;
  font-size: 1.4rem;
}


</style>
</head>

home/templates/home/components/offer_applying.html
{% include 'home/components/mail_style.html' %}
<body>

<h2 class="heading "> Postulation pour le poste : {{ post }} <h2>
    <p ><b>Nom: </b>{{ last_name }}</p>
    <p ><b>Prenom: </b>{{ first_name }}</p>
    <p ><b>E-mail: </b>{{ email }}</p>
    <p ><b>Telephone:</b>0{{ cellphone }}</p>
    <div class="message">
      <p> {{ content }}</p>
    </div> 
    <a href="mailto:{{ email }}" class="btn"> Repondre </a>
</body> 

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %} 

<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css">

{% endblock %}

{% block content %}

{% include 'home/components/header.html' %}
<section class="hero">
    <div class="hero__content">
      <span class="hero__title">M4Concept</span>
      <h3 class="hero__description">Société de prestations de services aux Entreprises</h3>
      <a href="/contact-us" class="btn">Contactez Nous</a>
    </div>
</section>

<section id="about" class="about">
  <div class="sidebyside_element">
    <div class="side__image" data-aos="fade-right">
      
      <img src="{% static 'home/assets/images/svg/Law firm-pana.svg' %}" alt="" />
    </div>
    <div class="side__content" data-aos="zoom-in-left">
      <h3 class="side__title">Qui Sommes-Nous ?</h3>
        <p class="side__description"> M4 Concept est une entreprise de droits congolais, qui
        évolue dans les prestations des services nous offrons une large
        gamme de service pour une clientéle diversifiée, que vous soyez une
        entreprise ou un particulier. Nous mettons un point d'honneur à
        répondre au mieux a tous les besions de nos clients, en leur offrant
        des prix compétitifs qui respectent leur budget et en les
        satisfaisant avec le meilleur service du marché</p>
      <a href="{% url 'home:about-us' %}" class="btn">Savoir plus</a>
      <br>
    </div>
  </div>

  <div class="sidebyside_element">
    
    <div class="side__content" data-aos="zoom-in-left">
      <h3 class="side__title">Nos Valeurs</h3>
      <p class="side__description">Le savoir être ,le savoir-faire ,l'efficaté , la fiabilité et la rigueur 
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas aliquid amet aliquam ea esse? Unde quam quasi tempora cum voluptates?</p>
    </div>
    <div class="side__image" data-aos="fade-right">
      <img src="{% static 'home/assets/images/svg/Law firm-bro.svg' %}" alt=""></img>
    </div>

  </div>

  <div class="sidebyside_element">
    <div class="side__image" data-aos="fade-right">
      <img src="{% static 'home/assets/images/svg/Goal-bro.svg' %}" alt=""></img> 
    </div>
    <div class="side__content" data-aos="zoom-in-left">
      <h3 class="side__title">Notre Mission</h3>
      <ul class="side__list">
        <li class="side__list_item">Apporter des solutions aux problèmes de notre client</li>
        <br />
        <li class="side__list_item">Apporter un soutien professionnel à nos clients</li>
      </ul>
    </div>

  </div>
</section>


<section class="services" id="services">
  <h1 class="heading">Nos <span class="heading--primary">services</span></h1>

<div class="grid grid--autofit-30 grid--gap-2">
    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/jardinier.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/jardinier.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/jardinier.jfif' %}" alt="">
      </picture>
      
      <p class="service__title">Entretien D'espace vert </p>
    </div>

    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/cleaner.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/cleaner.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/cleaner.jfif' %}" alt="">
      </picture>
      
      <p class="service__title">Technicienne de Surface</p>
    </div>
    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/téléchargement.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/jardinier.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/téléchargement.jfif' %}" alt="">
      </picture>
      
      <p class="service__title">Agent de securité </p>
    </div>

    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/market.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/market.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/market.jfif' %}" alt="">
      </picture>
      <p class="service__title">Gestion de projet </p>
    </div>

    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/informatique.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/informatique.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/informatique.jfif' %}" alt="">
      </picture>
      <p class="service__title">Informatique</p>
    </div>
    <div class="box">
      <picture >
        <source 
          type="image/webp"
          srcset = "{% static 'home/assets/images/webp/market2.webp' %}"
        />
        <source 
          type="image/jfif"
          srcset = "{% static 'home/assets/images/market2.jfif' %}"
        />
        <img class="service__image" src="{% static 'home/assets/images/market2.jfif' %}" alt="">
      </picture>
      <p class="service__title">Etude du marché </p>
    </div>

</div>
</section>
<section  id="work">
  <h1 class="heading">Notre <span class="heading--primary">Travail</span></h1>

  <div class="image_grid ">
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/cleaner.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/cleaner.jfif' %}"
      />
      <img src="{% static 'home/assets/images/cleaner.jfif' %}" alt="" data-aos="fade-right">
    </picture>
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/jardinier.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/jardinier.jfif' %}"
      />
      <img src="{% static 'home/assets/images/jardinier.jfif ' %}" alt="" data-aos="zoom-in-left">
    </picture>
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/m45.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/m45.jfif' %}"
      />
      <img src="{% static 'home/assets/images/m45.jpg' %}" alt="" data-aos="fade-right">
    </picture>
    
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/informatique2.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/informatique2.jfif' %}"
      />
      <img src="{% static 'home/assets/images/informatique2.jfif' %}" alt=""data-aos="zoom-in-left">
    </picture>

    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/jardinier2.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/jardinier2.jfif' %}"
      />
      <img src="{% static 'home/assets/images//jardinier2.jfif'  %}" alt="" data-aos="fade-right">
    </picture>
     
    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/images.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/images.jfif' %}"
      />
      <img src="{% static 'home/assets/images/images.jfif' %}" alt="" data-aos="zoom-in-left">
    </picture>

    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/market.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/market.jfif' %}"
      />
      <img src="{% static 'home/assets/images/market.jfif' %}" alt="" data-aos="fade-right">
    </picture>

    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/m46.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/m46.jfif' %}"
      />
      <img src="{% static 'home/assets/images/m46.jpg'  %}" alt="" data-aos="fade-right">
    </picture>

    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/informatique.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/informatique.jfif' %}"
      />
      <img src="{% static 'home/assets/images/informatique.jfif'  %}" alt="" data-aos="zoom-in-left">
    </picture>

    <picture >
      <source 
        type="image/webp"
        srcset = "{% static 'home/assets/images/webp/market2.webp' %}"
      />
      <source 
        type="image/png"
        srcset = "{% static 'home/assets/images/market2.jfif' %}"
      />
      <img src="{% static 'home/assets/images/market2.jfif'  %}" alt="" data-aos="fade-right">
    </picture>

  </div>
</section>


<section  class="partners" id="products">
  <h1 class="heading">Nos <span class="heading--primary">Partenaires</span></h1>

  <div class="swiper partners-slider ">
    <div class="swiper-wrapper" >

      <div class="swiper-slide slider" data-product="product-1">
        <img src="{% static 'home/assets/images/bralico.jpg'  %}" alt="" />
      </div>

      <div class="swiper-slide slider" data-product="product-2">
        <img src="{% static 'home/assets/images/brasco.jpg'  %}" alt="" />
      </div>

      <div class="swiper-slide slider" data-product="product-3">
        <img src="{% static 'home/assets/images/tractafric.jpg' %}" alt="" />
      </div> 
    </div>
  </div>
</section>



   {% include  'home/components/footer.html' %}
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>
<script>
  AOS.init();
</script>
{% endblock %}

home/templates/home/offers.html
{% extends 'base.html' %} {% load static %} {% block head %} {% endblock %}
{%block content %} 
{% include 'home/components/header.html' %}

<section class="hero hero--small">
  <div class="hero__content">
    <h3 class="hero__description">Nos Offres</h3>
  </div>
</section>

{% if offers %}
<section class="offer_section card">
  <h1 class="heading">
    Postuler a nos <span class="heading--primary">offres d'emploi</span>
  </h1>
  {% for offer in offers %}
  <div class="offer">
    <h2 class="offer__heading">
      Post : <strong>{{ offer.searching_for }}</strong>
    </h2>
    <h2 class="offer__heading offer__heading--sm">
      type de contrat: <strong>{{ offer.contract }} </strong>
    </h2>
    <div class="offer__description">{{ offer.description|safe }}</div>
    <div class="offer__description">
      {{ offer.looking_for|safe }}
    </div>
    <span class="offer__subtitle"
      >experience : <strong>{{ offer.experience }} </strong>
    </span>
    <span class="offer__subtitle"
      >nombre de poste: <strong>{{ offer.post_number }}</strong></span
    >
    <span class="offer__subtitle"
      >Region: <strong>{{ offer.region }}</strong></span
    >
    <div class="btn__container">
      <a href="{% url 'home:apply' slug=offer.slug %}" class="btn">postuler</a>
    </div>
    <div class="offer__endline"></div>
  </div>
  {% endfor %}
</section>
<section></section>
{% else %}
<section class="heading">Aucune offre Disponible</section>

<section class="home"></section>
<section class="home"></section>
{% endif %} 
{% include 'home/components/footer.html' %} 
{% endblock%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'home/assets/icons/favicon.ico' %}" />
    <meta name="description" content="M4Concept est une entreprise de droits congolais, qui évolue dans les prestations des Services ...">
    <meta property="og:title" content="M4 Concept">
    <meta property="og:description" content="M4Concept est une entreprise de droits congolais, qui
    évolue dans les prestations des Services">
    <meta property="og:url" content="http:s//">
    <meta property="og:image" content="">
    <link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">

    {% block head %} {% endblock %}

    <title>M4Concept</title>
  </head>
  <body>
    {% block content %} {% endblock %}

    <script src="{% static 'home/js/scripts.min.js' %}"></script>
  </body>
</html>